{% set version = "0.1.9.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pathdiagram
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pathdiagram_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pathdiagram/pathdiagram_{{ version }}.tar.gz
  sha256: 652f7a17fa40094191d0b726d50b7a9336314bb52b4a814c700bf461c3ce0e05

build:
  merge_build_host: True  # [win]
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-shape
  run:
    - r-base
    - r-shape

test:
  commands:
    - $R -e "library('pathdiagram')"           # [not win]
    - "\"%R%\" -e \"library('pathdiagram')\""  # [win]

about:
  home: http://www.gastonsanchez.com
  license: GPL-3
  summary: Implementation of simple functions to draw basic path diagrams just for visualization
    purposes.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - PertuyF

# Package: pathdiagram
# Type: Package
# Title: Basic functions for drawing path diagrams
# Version: 0.1.9
# Date: 2013-07-28
# Author: Gaston Sanchez
# Maintainer: Gaston Sanchez <gaston.stat@gmail.com>
# Description: Implementation of simple functions to draw basic path diagrams just for visualization purposes.
# URL: http://www.gastonsanchez.com
# Depends: R (>= 3.0), shape
# Suggests: knitr
# VignetteBuilder: knitr
# License: GPL-3
# Collate: 'arrow.R' 'draw.R' 'latent.R' 'manifest.R' 'wall.R'
# Packaged: 2013-07-29 17:53:31 UTC; Gaston
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2013-07-29 19:57:33
